# 🐳 DOCKER COMPOSE PARA SISTEMA DE TRADING V2.0
# ===============================================

version: '3.8'

services:
  # Servicio principal del sistema de trading
  trading-system:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: trading_system_v2
    restart: unless-stopped
    
    # Variables de entorno
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=America/New_York
      - DEVELOPMENT_MODE=${DEVELOPMENT_MODE:-false}
      - TEST_MODE=${TEST_MODE:-false}
    
    # Variables desde archivo .env
    env_file:
      - .env
    
    # Volúmenes para persistir logs y configuración
    volumes:
      - ./logs:/app/logs
      - ./config.py:/app/config.py
      - ./.env:/app/.env
    
    # Configuración de red
    networks:
      - trading_network
    
    # Healthcheck
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Servicio opcional: Monitor de logs
  log-monitor:
    image: alpine:latest
    container_name: trading_logs_monitor
    command: tail -f /logs/trading_system.log
    volumes:
      - ./logs:/logs
    depends_on:
      - trading-system
    networks:
      - trading_network
    profiles:
      - monitoring

# Red personalizada
networks:
  trading_network:
    driver: bridge

# Volúmenes nombrados (opcional)
volumes:
  trading_logs:
    driver: local